#!/usr/bin/env bash
# Transfer a file to a Remote server

# Check if the correct number of parameters is provided
if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Extract parameters
FILE_PATH=$1
SERVER_IP=$2
USERNAME=$3
SSH_KEY=$4

# Transfer file using scp with strict host key checking disabled
scp -o StrictHostKeyChecking=no -i "$SSH_KEY" "$FILE_PATH" "$USERNAME"@"$SERVER_IP":~/
