#!/usr/bin/env bash
# Install nginx web server

# Update the package list on the system
sudo apt -y update

# Install nginx
sudo apt -y install nginx

# Create a custom HTML file with "Hello World!" for default website
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'

# Start automatically nginxt at boot
sudo systemctl enable nginx

# Start nginx service
sudo service nginx start
