#!/usr/bin/env bash
# Stop the 4-to_infinity_and_beyond process using kill

# Get the pid of the program
id=$(pgrep "bash ./4-to_infinity_and_beyond" -f)

# Terminate the infinate process
if [ -n "$id" ]
then
    kill -15 "$id"
fi
