#!/usr/bin/env bash
# Configure localhost to resolve 127.0.0.2 and facebook to resolve 8.8.8.8

# Copy /etc/hosts to ~/hosts.new
cp /etc/hosts ~/hosts.new

# Set localhost to resolve 127.0.0.2 instead of 127.0.0.1
sed -i "s/^127[0-9.]*\slocalhost/127.0.0.2 localhost/" ~/hosts.new

# Set facebook.com to resolve 8.8.8.8
sed -i "$ a\8.8.8.8 facebook.com" ~/hosts.new

# Copy the new hosts file to /etc/hosts
sudo cp -f ~/hosts.new /etc/hosts
